apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.31.0
    releaseName: vault
    valuesFile: values.yaml
